spring.application.name=ai-knowledgeassistant
server.port=8081


# DATABASE CONFIGURATION

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# SPRING AI CONFIGURATION

spring.ai.openai.api-key=${OPENAI_API_KEY:dummy}

spring.ai.openai.chat.api-key=${DEEPSEEK_API_KEY:dummy}
spring.ai.openai.chat.base-url=https://api.deepseek.com
spring.ai.openai.chat.options.model=deepseek-chat

spring.ai.openai.embedding.options.model=text-embedding-3-large


# ACTUATOR

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always